---
abstract: 'Serialize the stash as XML using XML::Generator::PerlData'
author:
  - 'Michael Nachbaurt <mike@nachbaur.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-XML-Generator
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::View: 0
  XML::Generator::PerlData: 0
  XML::SAX::Writer: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
